import type { Case } from "@/types/investigation";

export const case001: Case = {
  id: "001",
  number: "001",
  title: "The Last Guest at Blackwood Manor",
  difficulty: "Medium",
  duration: "25 min",
  location: "Blackwood Manor, Upper Thames",
  date: "12 November 1928",
  summary:
    "A private supper at Blackwood Manor ended before the dessert wine was poured. Edmund Vale was found in the conservatory with the terrace doors ajar and a letter that was never signed.",
  victim: {
    name: "Edmund Vale",
    role: "The Host",
    initials: "EV",
    summary:
      "A widower of means and a collector of private correspondences. He invited three familiar faces and one guest who was not on the original card. He never returned from the conservatory.",
  },
  suspects: [
    {
      id: "clara",
      name: "Clara Vale",
      initials: "CV",
      role: "The Widow",
      relationship: "Sister-in-law; recently dependent on Edmund’s estate",
      bio: "Composed, exacting, and rarely seen without a glass she does not finish. She sat at Edmund’s right through the first four courses.",
      background:
        "Clara married into the Vale family eight years ago. After her husband’s death she remained at Blackwood under Edmund’s protection — a kindness that had begun to feel like a ledger.",
      alibi: "Claims she left the dining room at 10:30 PM and retired to the east wing.",
      suspicion: "elevated",
      questioned: true,
      connectedEvidenceIds: ["receipt", "photograph", "letter"],
    },
    {
      id: "silas",
      name: "Dr. Silas Rowe",
      initials: "SR",
      role: "The Physician",
      relationship: "Long-time physician and wartime acquaintance",
      bio: "Soft-spoken, precise with time, and first to suggest the conservatory be closed for the season.",
      background:
        "Rowe attended Edmund through two winters of nervous complaints. He arrived tonight with his bag already packed, as if he expected to be needed.",
      alibi: "Says he left the dining room at 10:52 PM to retrieve his medical bag from the cloakroom.",
      suspicion: "watching",
      questioned: false,
      connectedEvidenceIds: ["watch", "statement", "vial"],
    },
    {
      id: "jonah",
      name: "Jonah Pike",
      initials: "JP",
      role: "The Valet",
      relationship: "Household valet for eleven years",
      bio: "Knows every corridor by sound. He poured the champagne and was the last staff member seen near the terrace.",
      background:
        "Pike has served the Vales since he was nineteen. He keeps the keys, the cellar book, and a silence that staff describe as loyal — or convenient.",
      alibi: "Maintains he was polishing silver in the pantry from 10:40 until the house was raised.",
      suspicion: "unclear",
      questioned: false,
      connectedEvidenceIds: ["coupe", "glove", "cctv"],
    },
    {
      id: "isolde",
      name: "Isolde Hart",
      initials: "IH",
      role: "The Unexpected Guest",
      relationship: "Unlisted guest; arrived with an unsigned letter",
      bio: "Arrived twenty minutes late, declined wine, and asked twice to see the conservatory before supper was finished.",
      background:
        "Little is recorded of Miss Hart. The guest book shows no prior visit. She claims a professional matter with Edmund that could not wait until morning.",
      alibi: "Says she was in the gallery studying the portraits when the clock struck eleven.",
      suspicion: "watching",
      questioned: false,
      connectedEvidenceIds: ["letter", "phone", "hallway"],
    },
  ],
  evidence: [
    {
      id: "cctv",
      fileNumber: "EV-04",
      title: "West Hallway Plate",
      kind: "cctv",
      description:
        "A house camera plate above the west corridor recorded a figure passing toward the conservatory at 11:08. The face is lost to the lamp glare.",
      timestamp: "11:08 PM",
      location: "West hallway, first floor",
      relatedSuspectId: "jonah",
      discovered: true,
      imageLabel: "PLATE 11:08",
    },
    {
      id: "receipt",
      fileNumber: "EV-07",
      title: "Cellar Receipt",
      kind: "receipt",
      description:
        "A torn receipt for a 1919 champagne, charged to C. Vale two days before the supper. The second bottle was never entered in the cellar book.",
      timestamp: "10 November 1928",
      location: "Butler’s ledger, pantry",
      relatedSuspectId: "clara",
      discovered: true,
      imageLabel: "LEDGER SLIP",
    },
    {
      id: "phone",
      fileNumber: "EV-09",
      title: "House Telephone Slip",
      kind: "phone",
      description:
        "A message taken at the hall telephone: “Do not sign it until I arrive.” The operator logged the call under Hart, I.",
      timestamp: "9:14 PM",
      location: "Front hall telephone",
      relatedSuspectId: "isolde",
      discovered: true,
      imageLabel: "EXCHANGE NOTE",
    },
    {
      id: "photograph",
      fileNumber: "EV-02",
      title: "Supper Photograph",
      kind: "photograph",
      description:
        "A plate taken before the fish course. Edmund is smiling. Clara’s hand is not on the table. Isolde is turned toward the terrace doors.",
      timestamp: "9:50 PM",
      location: "Dining room",
      relatedSuspectId: "clara",
      discovered: true,
      imageLabel: "PLATE VII",
    },
    {
      id: "statement",
      fileNumber: "EV-11",
      title: "Kitchen Statement",
      kind: "statement",
      description:
        "The kitchen maid heard Dr. Rowe in the cloakroom after 10:50, then a second voice she could not name. She did not see who left for the conservatory.",
      timestamp: "Taken 12:40 AM",
      location: "Servants’ hall",
      relatedSuspectId: "silas",
      discovered: true,
      imageLabel: "STMT 01",
    },
    {
      id: "coupe",
      fileNumber: "EV-01",
      title: "Broken Champagne Coupe",
      kind: "object",
      description:
        "A crystal coupe shattered on the conservatory tiles. The stem is intact. There is no champagne in the glass — only a pale residue.",
      timestamp: "Found 11:31 PM",
      location: "Conservatory floor",
      relatedSuspectId: "jonah",
      discovered: true,
      imageLabel: "OBJECT A",
    },
    {
      id: "letter",
      fileNumber: "EV-03",
      title: "Unsigned Letter",
      kind: "object",
      description:
        "A letter on cream stock, half-finished, in Edmund’s hand. It begins “If you have come for what I kept—” and ends without a signature.",
      timestamp: "Found 11:31 PM",
      location: "Conservatory writing table",
      relatedSuspectId: "isolde",
      discovered: true,
      imageLabel: "DOC 03",
    },
    {
      id: "glove",
      fileNumber: "EV-05",
      title: "Muddy Evening Glove",
      kind: "object",
      description:
        "A left evening glove, damp at the fingertips, found beneath the terrace step. The pair belongs to the household set issued to staff.",
      timestamp: "Found 11:44 PM",
      location: "Terrace, south door",
      relatedSuspectId: "jonah",
      discovered: true,
      imageLabel: "OBJECT B",
    },
    {
      id: "watch",
      fileNumber: "EV-06",
      title: "Stopped Pocket Watch",
      kind: "object",
      description:
        "Edmund’s watch, face cracked, hands fixed at 11:17. It was not on his person. It was in the study, as if set down and never collected.",
      timestamp: "Stopped 11:17 PM",
      location: "Study, writing desk",
      relatedSuspectId: "silas",
      discovered: true,
      imageLabel: "OBJECT C",
    },
    {
      id: "key",
      fileNumber: "EV-08",
      title: "Study Key",
      kind: "object",
      description: "The spare key to the study is missing from the valet’s board.",
      timestamp: "Unknown",
      location: "Key board, servants’ passage",
      relatedSuspectId: "jonah",
      discovered: false,
      imageLabel: "SEALED",
    },
    {
      id: "soil",
      fileNumber: "EV-10",
      title: "Conservatory Soil",
      kind: "object",
      description: "A transfer of soil from the terrace beds, found on a hem.",
      timestamp: "Unknown",
      location: "Conservatory threshold",
      relatedSuspectId: null,
      discovered: false,
      imageLabel: "SEALED",
    },
    {
      id: "guestbook",
      fileNumber: "EV-12",
      title: "Guest Book Page",
      kind: "photograph",
      description: "A page that may show who was expected — and who was not.",
      timestamp: "Unknown",
      location: "Entrance hall",
      relatedSuspectId: "isolde",
      discovered: false,
      imageLabel: "SEALED",
    },
    {
      id: "vial",
      fileNumber: "EV-13",
      title: "Pharmacy Vial",
      kind: "object",
      description: "A small vial from Rowe’s bag, unlabelled except for a date.",
      timestamp: "Unknown",
      location: "Physician’s bag",
      relatedSuspectId: "silas",
      discovered: false,
      imageLabel: "SEALED",
    },
  ],
  timeline: [
    {
      id: "t1",
      time: "10:30 PM",
      title: "Clara Vale claims to leave",
      detail:
        "Clara states she excused herself after the game course and went to the east wing. No staff confirm seeing her on the stair.",
      suspectId: "clara",
    },
    {
      id: "t2",
      time: "10:42 PM",
      title: "Victim enters the study",
      detail:
        "Edmund was seen crossing the inner hall with a folded letter. The study lamp was lit for six minutes.",
      suspectId: null,
    },
    {
      id: "t3",
      time: "10:52 PM",
      title: "Dr. Rowe leaves the dining room",
      detail:
        "Rowe rose without finishing his wine and walked toward the cloakroom, citing a forgotten bag.",
      suspectId: "silas",
    },
    {
      id: "t4",
      time: "11:02 PM",
      title: "Isolde seen in the gallery",
      detail:
        "A portrait light was found burning. Isolde says she was alone with the family pictures.",
      suspectId: "isolde",
    },
    {
      id: "t5",
      time: "11:08 PM",
      title: "Movement in the west hallway",
      detail:
        "The house plate recorded a figure moving toward the conservatory. The face is unreadable.",
      suspectId: "jonah",
    },
    {
      id: "t6",
      time: "11:17 PM",
      title: "Estimated time of incident",
      detail:
        "The pocket watch stopped. The conservatory doors were found ajar shortly after.",
      suspectId: null,
    },
  ],
};
